/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The current user, provisioned on first sight (TR-AUTH-03), with their workspaces.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace
         * @description Also remembers this workspace as the user's last one, for /app (F-02).
         */
        get: operations["get_workspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Workspace */
        patch: operations["update_workspace"];
        trace?: never;
    };
    "/v1/w/{wid}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Checklist */
        Checklist: {
            /** Completed */
            completed: number;
            /** Dismissed */
            dismissed: boolean;
            /** Steps */
            steps: components["schemas"]["ChecklistStep"][];
        };
        /** ChecklistStep */
        ChecklistStep: {
            /** Done */
            done: boolean;
            /**
             * Key
             * @enum {string}
             */
            key: "connect_account" | "add_knowledge" | "choose_ai_mode" | "create_automation";
        };
        /** Me */
        Me: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Workspace Id */
            last_workspace_id?: string | null;
            /** Name */
            name?: string | null;
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        /** Overview */
        Overview: {
            checklist: components["schemas"]["Checklist"];
            /**
             * Range
             * @enum {string}
             */
            range: "7d" | "30d";
        };
        /** Problem */
        Problem: {
            /** Code */
            code: string;
            /** Detail */
            detail?: string;
            /** Errors */
            errors?: {
                /** Field */
                field: string;
                /** Message */
                message: string;
            }[];
            /** Request Id */
            request_id?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** WorkspaceList */
        WorkspaceList: {
            /** Items */
            items: components["schemas"]["WorkspaceSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /** Automation Disclosure */
            automation_disclosure?: string | null;
            /** Checklist Dismissed At */
            checklist_dismissed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "pro" | "max";
            /** Reply Language */
            reply_language: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "agent";
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "deleting";
            /** Timezone */
            timezone: string;
        };
        /** WorkspacePatch */
        WorkspacePatch: {
            /** Automation Disclosure */
            automation_disclosure?: string | null;
            /** Checklist Dismissed */
            checklist_dismissed?: boolean | null;
            /** Name */
            name?: string | null;
            /** Reply Language */
            reply_language?: string | null;
            /** Slug */
            slug?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "pro" | "max";
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "agent";
            /** Slug */
            slug: string;
            /** Timezone */
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspacePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_overview: {
        parameters: {
            query?: {
                range?: "7d" | "30d";
            };
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceList"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
