/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/data-deletion/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Deletion Status */
        get: operations["get_data_deletion_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The current user, provisioned on first sight (TR-AUTH-03), with their workspaces.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace
         * @description Also remembers this workspace as the user's last one, for /app (F-02).
         */
        get: operations["get_workspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Workspace */
        patch: operations["update_workspace"];
        trace?: never;
    };
    "/v1/w/{wid}/dev/sandbox/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Sandbox Account
         * @description Connect a fake Instagram account for local development.
         */
        post: operations["create_sandbox_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/dev/sandbox/inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sandbox Inbound
         * @description Inject a fake DM or comment. It goes through the same intake as a real webhook.
         */
        post: operations["sandbox_inbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notifications Read */
        post: operations["mark_notifications_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Social Accounts */
        get: operations["list_social_accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts/instagram/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Instagram Connect */
        post: operations["start_instagram_connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect Social Account */
        delete: operations["disconnect_social_account"];
        options?: never;
        head?: never;
        /** Update Social Account */
        patch: operations["update_social_account"];
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts/{account_id}/resubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resubscribe Social Account
         * @description Retry the webhook subscription after it failed (F-03 edge case).
         */
        post: operations["resubscribe_social_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Checklist */
        Checklist: {
            /** Completed */
            completed: number;
            /** Dismissed */
            dismissed: boolean;
            /** Steps */
            steps: components["schemas"]["ChecklistStep"][];
        };
        /** ChecklistStep */
        ChecklistStep: {
            /** Done */
            done: boolean;
            /**
             * Key
             * @enum {string}
             */
            key: "connect_account" | "add_knowledge" | "choose_ai_mode" | "create_automation";
        };
        /** ConnectStart */
        ConnectStart: {
            /** Authorize Url */
            authorize_url: string;
        };
        /** DataDeletionStatus */
        DataDeletionStatus: {
            /** Completed At */
            completed_at?: string | null;
            /** Confirmation Code */
            confirmation_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "received" | "processing" | "completed";
        };
        /** MarkRead */
        MarkRead: {
            /**
             * All
             * @default false
             */
            all: boolean;
            /** Ids */
            ids?: string[] | null;
        };
        /** Me */
        Me: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Workspace Id */
            last_workspace_id?: string | null;
            /** Name */
            name?: string | null;
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        /** NotificationList */
        NotificationList: {
            /** Items */
            items: components["schemas"]["NotificationOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Unread Count */
            unread_count: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Link */
            link?: string | null;
            /** Read At */
            read_at?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** Overview */
        Overview: {
            checklist: components["schemas"]["Checklist"];
            /**
             * Range
             * @enum {string}
             */
            range: "7d" | "30d";
        };
        /** Problem */
        Problem: {
            /** Code */
            code: string;
            /** Detail */
            detail?: string;
            /** Errors */
            errors?: {
                /** Field */
                field: string;
                /** Message */
                message: string;
            }[];
            /** Request Id */
            request_id?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** SandboxInbound */
        SandboxInbound: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** From Id */
            from_id?: string | null;
            /** From Username */
            from_username?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dm" | "comment";
            /** Text */
            text: string;
        };
        /** SandboxInboundResult */
        SandboxInboundResult: {
            /** Stored */
            stored: number;
        };
        /** SocialAccountList */
        SocialAccountList: {
            /** Items */
            items: components["schemas"]["SocialAccountOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * SocialAccountOut
         * @description Never the token itself (SEC-02).
         */
        SocialAccountOut: {
            /** Ai Analysis Enabled */
            ai_analysis_enabled: boolean;
            /**
             * Ai Mode
             * @enum {string}
             */
            ai_mode: "off" | "suggest" | "auto";
            /** Auto Hide Spam */
            auto_hide_spam: boolean;
            /** Capabilities */
            capabilities: ("dm_send" | "dm_attachments" | "read_receipts" | "human_agent" | "templates" | "conversation_backfill" | "comments" | "private_reply" | "publish" | "post_insights" | "account_insights")[];
            /** Connected At */
            connected_at?: string | null;
            /** Display Name */
            display_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Error */
            last_error?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /**
             * Platform
             * @enum {string}
             */
            platform: "instagram" | "whatsapp";
            /** Profile Picture Url */
            profile_picture_url?: string | null;
            /**
             * Sandbox
             * @default false
             */
            sandbox: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "needs_reconnect" | "disconnected" | "error";
            /** Token Expires At */
            token_expires_at?: string | null;
            /** Username */
            username?: string | null;
        };
        /** SocialAccountPatch */
        SocialAccountPatch: {
            /** Ai Analysis Enabled */
            ai_analysis_enabled?: boolean | null;
            /** Ai Mode */
            ai_mode?: ("off" | "suggest" | "auto") | null;
            /** Auto Hide Spam */
            auto_hide_spam?: boolean | null;
            /** Display Name */
            display_name?: string | null;
        };
        /** WorkspaceList */
        WorkspaceList: {
            /** Items */
            items: components["schemas"]["WorkspaceSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /** Automation Disclosure */
            automation_disclosure?: string | null;
            /** Checklist Dismissed At */
            checklist_dismissed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "pro" | "max";
            /** Reply Language */
            reply_language: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "agent";
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "deleting";
            /** Timezone */
            timezone: string;
        };
        /** WorkspacePatch */
        WorkspacePatch: {
            /** Automation Disclosure */
            automation_disclosure?: string | null;
            /** Checklist Dismissed */
            checklist_dismissed?: boolean | null;
            /** Name */
            name?: string | null;
            /** Reply Language */
            reply_language?: string | null;
            /** Slug */
            slug?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "pro" | "max";
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "agent";
            /** Slug */
            slug: string;
            /** Timezone */
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_data_deletion_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataDeletionStatus"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspacePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_sandbox_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    sandbox_inbound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxInbound"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxInboundResult"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_notifications: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    mark_notifications_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkRead"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_overview: {
        parameters: {
            query?: {
                range?: "7d" | "30d";
            };
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_social_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    start_instagram_connect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectStart"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    disconnect_social_account: {
        parameters: {
            query?: {
                delete_data?: boolean;
            };
            header?: never;
            path: {
                account_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_social_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialAccountPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resubscribe_social_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceList"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
