/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/data-deletion/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Deletion Status */
        get: operations["get_data_deletion_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The current user, provisioned on first sight (TR-AUTH-03), with their workspaces.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace
         * @description Also remembers this workspace as the user's last one, for /app (F-02).
         */
        get: operations["get_workspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Workspace */
        patch: operations["update_workspace"];
        trace?: never;
    };
    "/v1/w/{wid}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/conversations/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inbox Counts */
        get: operations["get_inbox_counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Conversation
         * @description Archive or unarchive; set or clear the conversation's AI mode override.
         */
        patch: operations["update_conversation"];
        trace?: never;
    };
    "/v1/w/{wid}/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description Newest first; next_cursor loads older messages (upward infinite scroll).
         */
        get: operations["list_messages"];
        put?: never;
        /**
         * Send Message
         * @description Queue a reply; it is sent by the worker and progress arrives as message.updated events.
         *
         *     Any member may reply. The same Idempotency-Key with the same body returns the first response
         *     and sends nothing more; with a different body it is 409 idempotency_conflict.
         */
        post: operations["send_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/conversations/{conversation_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Conversation Read */
        post: operations["mark_conversation_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/conversations/{conversation_id}/scheduled-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversation Scheduled Messages
         * @description The conversation's pending (scheduled or sending) messages, soonest first.
         */
        get: operations["list_conversation_scheduled_messages"];
        put?: never;
        /**
         * Create Scheduled Message
         * @description send_at must be at least 2 minutes away and 5 minutes before the reply window closes.
         */
        post: operations["create_scheduled_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/conversations/{conversation_id}/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Conversation Unread */
        post: operations["mark_conversation_unread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/dev/sandbox/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Sandbox Account
         * @description Connect a fake Instagram account for local development.
         */
        post: operations["create_sandbox_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/dev/sandbox/inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sandbox Inbound
         * @description Inject a fake DM or comment. It goes through the same intake as a real webhook.
         */
        post: operations["sandbox_inbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/media-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Media Asset
         * @description Register an uploaded file: it must be in this workspace's folder (else 422 on public_id)
         *     and within the limits (else 415 unsupported_media). Registering it again returns it.
         */
        post: operations["register_media_asset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/media-assets/upload-signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Upload Signature
         * @description Parameters for uploading one file from the browser into ws/{workspace_id}/{purpose}.
         */
        post: operations["create_upload_signature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/messages/{message_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Message
         * @description Send a failed message again (the same row). A message already queued or sending is
         *     returned as it is, so a second click never sends it twice.
         */
        post: operations["retry_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notifications Read */
        post: operations["mark_notifications_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/scheduled-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scheduled Messages
         * @description The Scheduled tab: pending first by send time, then recent sent, failed and expired.
         */
        get: operations["list_scheduled_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/scheduled-messages/{scheduled_message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel Scheduled Message
         * @description Cancel while the message is still scheduled (409 conflict after that).
         */
        delete: operations["cancel_scheduled_message"];
        options?: never;
        head?: never;
        /**
         * Update Scheduled Message
         * @description Edit the text or time while the message is still scheduled (409 conflict after that).
         */
        patch: operations["update_scheduled_message"];
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Social Accounts */
        get: operations["list_social_accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts/instagram/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Instagram Connect */
        post: operations["start_instagram_connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts/whatsapp/embedded-signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Whatsapp Signup
         * @description Finish Embedded Signup: store the number and subscribe to its webhooks. 409
         *     account_in_use when the number is connected to another workspace.
         */
        post: operations["complete_whatsapp_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect Social Account */
        delete: operations["disconnect_social_account"];
        options?: never;
        head?: never;
        /** Update Social Account */
        patch: operations["update_social_account"];
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts/{account_id}/resubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resubscribe Social Account
         * @description Retry the webhook subscription after it failed (F-03 edge case).
         */
        post: operations["resubscribe_social_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/w/{wid}/social-accounts/{account_id}/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Whatsapp Templates
         * @description Approved message templates for the template picker (sends outside the 24 h window).
         */
        get: operations["list_whatsapp_templates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Actor */
        Actor: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
        };
        /** Attachment */
        Attachment: {
            /** Duration S */
            duration_s?: number | null;
            /** Expired */
            expired?: boolean | null;
            /** Filename */
            filename?: string | null;
            /** Height */
            height?: number | null;
            /** Id */
            id: string;
            /** Mime Type */
            mime_type?: string | null;
            /** Permalink */
            permalink?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "image" | "video" | "audio" | "file" | "sticker" | "story" | "share";
            /** Url */
            url: string;
            /** Width */
            width?: number | null;
        };
        /** AutomationRef */
        AutomationRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** Checklist */
        Checklist: {
            /** Completed */
            completed: number;
            /** Dismissed */
            dismissed: boolean;
            /** Steps */
            steps: components["schemas"]["ChecklistStep"][];
        };
        /** ChecklistStep */
        ChecklistStep: {
            /** Done */
            done: boolean;
            /**
             * Key
             * @enum {string}
             */
            key: "connect_account" | "add_knowledge" | "choose_ai_mode" | "create_automation";
        };
        /** ConnectStart */
        ConnectStart: {
            /** Authorize Url */
            authorize_url: string;
        };
        /** ContactDetail */
        ContactDetail: {
            /** Display Name */
            display_name?: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Platform User Id */
            platform_user_id: string;
            /** Profile Picture Url */
            profile_picture_url?: string | null;
            /** Username */
            username?: string | null;
        };
        /** ContactSummary */
        ContactSummary: {
            /** Display Name */
            display_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Profile Picture Url */
            profile_picture_url?: string | null;
            /** Username */
            username?: string | null;
        };
        /** Conversation */
        Conversation: {
            ai: components["schemas"]["ConversationAi"];
            /** Awaiting Reply */
            awaiting_reply: boolean;
            contact: components["schemas"]["ContactDetail"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Message At */
            last_message_at?: string | null;
            /** Last Message Direction */
            last_message_direction?: ("inbound" | "outbound" | "system") | null;
            /** Last Message Kind */
            last_message_kind?: ("text" | "image" | "video" | "audio" | "file" | "sticker" | "story_mention" | "story_reply" | "share" | "template" | "location" | "unsupported" | "system") | null;
            /** Last Message Preview */
            last_message_preview?: string | null;
            /** Last Message Source */
            last_message_source?: ("customer" | "human" | "ai_auto" | "automation" | "native_app" | "system") | null;
            latest_analysis?: components["schemas"]["MessageAnalysis"] | null;
            /** Lead Score */
            lead_score?: number | null;
            /** Needs Human */
            needs_human: boolean;
            /** Needs Human Reason */
            needs_human_reason?: ("refund" | "legal" | "complaint" | "negative_sentiment" | "abuse" | "account_or_payment" | "human_requested" | "low_confidence" | "out_of_knowledge" | "window_closed" | "policy_keyword" | "output_blocked") | null;
            pending_suggestion?: components["schemas"]["Suggestion"] | null;
            /**
             * Platform
             * @enum {string}
             */
            platform: "instagram" | "whatsapp";
            reply_window: components["schemas"]["ReplyWindow"];
            /** Reply Window Closes At */
            reply_window_closes_at?: string | null;
            /** Scheduled Count */
            scheduled_count: number;
            /** Signal */
            signal?: ("needs_you" | "complaint" | "closing_soon" | "lead" | "negative") | null;
            social_account: components["schemas"]["ConversationAccount"];
            /**
             * Social Account Id
             * Format: uuid
             */
            social_account_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "archived";
            summary?: components["schemas"]["ConversationSummary"] | null;
            /** Unread Count */
            unread_count: number;
        };
        /** ConversationAccount */
        ConversationAccount: {
            /** Display Name */
            display_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Username */
            username?: string | null;
        };
        /** ConversationAi */
        ConversationAi: {
            /**
             * Effective Mode
             * @enum {string}
             */
            effective_mode: "off" | "suggest" | "auto";
            /** Override */
            override?: ("off" | "suggest" | "auto") | null;
            /** Paused Until */
            paused_until?: string | null;
        };
        /** ConversationList */
        ConversationList: {
            /** Items */
            items: components["schemas"]["ConversationListItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ConversationListItem */
        ConversationListItem: {
            /** Awaiting Reply */
            awaiting_reply: boolean;
            contact: components["schemas"]["ContactSummary"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Message At */
            last_message_at?: string | null;
            /** Last Message Direction */
            last_message_direction?: ("inbound" | "outbound" | "system") | null;
            /** Last Message Kind */
            last_message_kind?: ("text" | "image" | "video" | "audio" | "file" | "sticker" | "story_mention" | "story_reply" | "share" | "template" | "location" | "unsupported" | "system") | null;
            /** Last Message Preview */
            last_message_preview?: string | null;
            /** Last Message Source */
            last_message_source?: ("customer" | "human" | "ai_auto" | "automation" | "native_app" | "system") | null;
            /** Lead Score */
            lead_score?: number | null;
            /** Needs Human */
            needs_human: boolean;
            /** Needs Human Reason */
            needs_human_reason?: ("refund" | "legal" | "complaint" | "negative_sentiment" | "abuse" | "account_or_payment" | "human_requested" | "low_confidence" | "out_of_knowledge" | "window_closed" | "policy_keyword" | "output_blocked") | null;
            /**
             * Platform
             * @enum {string}
             */
            platform: "instagram" | "whatsapp";
            /** Reply Window Closes At */
            reply_window_closes_at?: string | null;
            /** Signal */
            signal?: ("needs_you" | "complaint" | "closing_soon" | "lead" | "negative") | null;
            /**
             * Social Account Id
             * Format: uuid
             */
            social_account_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "archived";
            /** Unread Count */
            unread_count: number;
        };
        /** ConversationPatch */
        ConversationPatch: {
            /** Ai Mode Override */
            ai_mode_override?: ("off" | "suggest" | "auto") | null;
            /**
             * Clear Ai Mode Override
             * @default false
             */
            clear_ai_mode_override: boolean;
            /** Status */
            status?: ("open" | "archived") | null;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Next Step */
            next_step?: string | null;
            /** Text */
            text: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DataDeletionStatus */
        DataDeletionStatus: {
            /** Completed At */
            completed_at?: string | null;
            /** Confirmation Code */
            confirmation_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "received" | "processing" | "completed";
        };
        /**
         * EmbeddedSignup
         * @description What the page receives from Meta's Embedded Signup v4 (FB.login code + session info).
         */
        EmbeddedSignup: {
            /** Code */
            code: string;
            /** Phone Number Id */
            phone_number_id: string;
            /** Waba Id */
            waba_id: string;
        };
        /** ErrorInfo */
        ErrorInfo: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * InboxCounts
         * @description The Inbox nav badge (FR-INB-04) and view chips.
         */
        InboxCounts: {
            /** Needs Reply */
            needs_reply: number;
            /** Needs You */
            needs_you: number;
            /** Unread */
            unread: number;
        };
        /** MarkRead */
        MarkRead: {
            /**
             * All
             * @default false
             */
            all: boolean;
            /** Ids */
            ids?: string[] | null;
        };
        /** Me */
        Me: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Workspace Id */
            last_workspace_id?: string | null;
            /** Name */
            name?: string | null;
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        /** MediaAssetCreate */
        MediaAssetCreate: {
            /** Public Id */
            public_id: string;
            /**
             * Resource Type
             * @enum {string}
             */
            resource_type: "image" | "video" | "raw";
        };
        /** MediaAssetOut */
        MediaAssetOut: {
            /** Bytes */
            bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration S */
            duration_s?: number | null;
            /** Format */
            format?: string | null;
            /** Height */
            height?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename?: string | null;
            /** Public Id */
            public_id: string;
            /** Purpose */
            purpose: string;
            /**
             * Resource Type
             * @enum {string}
             */
            resource_type: "image" | "video" | "raw";
            /** Secure Url */
            secure_url?: string | null;
            /** Width */
            width?: number | null;
        };
        /** Message */
        Message: {
            /** Attachments */
            attachments: components["schemas"]["Attachment"][];
            automation?: components["schemas"]["AutomationRef"] | null;
            /** Client Id */
            client_id?: string | null;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Delivered At */
            delivered_at?: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "inbound" | "outbound" | "system";
            error?: components["schemas"]["ErrorInfo"] | null;
            /** Human Agent Tag */
            human_agent_tag: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "image" | "video" | "audio" | "file" | "sticker" | "story_mention" | "story_reply" | "share" | "template" | "location" | "unsupported" | "system";
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reactions */
            reactions: components["schemas"]["Reaction"][];
            /** Read At */
            read_at?: string | null;
            /** Sent At */
            sent_at?: string | null;
            sent_by?: components["schemas"]["Actor"] | null;
            /**
             * Source
             * @enum {string}
             */
            source: "customer" | "human" | "ai_auto" | "automation" | "native_app" | "system";
            /** Status */
            status?: ("received" | "queued" | "sending" | "sent" | "delivered" | "read" | "failed") | null;
            /** Suggestion Id */
            suggestion_id?: string | null;
            template?: components["schemas"]["TemplateInfo"] | null;
            /** Text */
            text?: string | null;
        };
        /** MessageAnalysis */
        MessageAnalysis: {
            /** Corrected */
            corrected: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Intent
             * @enum {string}
             */
            intent: "pricing" | "product_inquiry" | "purchase" | "order_status" | "shipping" | "support" | "complaint" | "refund" | "feedback" | "collaboration" | "greeting" | "spam" | "other";
            /** Language */
            language: string;
            /** Lead Score */
            lead_score: number;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Needs Human */
            needs_human: boolean;
            /** Needs Human Reason */
            needs_human_reason?: ("refund" | "legal" | "complaint" | "negative_sentiment" | "abuse" | "account_or_payment" | "human_requested" | "low_confidence" | "out_of_knowledge" | "window_closed" | "policy_keyword" | "output_blocked") | null;
            /** Needs Reply */
            needs_reply: boolean;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
            /**
             * Sentiment
             * @enum {string}
             */
            sentiment: "positive" | "neutral" | "negative";
            /** Sentiment Score */
            sentiment_score: number;
            /** Topics */
            topics: string[];
        };
        /**
         * MessageList
         * @description Newest first; ``next_cursor`` fetches older messages.
         */
        MessageList: {
            /** Items */
            items: components["schemas"]["Message"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** NotificationList */
        NotificationList: {
            /** Items */
            items: components["schemas"]["NotificationOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Unread Count */
            unread_count: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Link */
            link?: string | null;
            /** Read At */
            read_at?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** Overview */
        Overview: {
            checklist: components["schemas"]["Checklist"];
            /**
             * Range
             * @enum {string}
             */
            range: "7d" | "30d";
        };
        /** Problem */
        Problem: {
            /** Code */
            code: string;
            /** Detail */
            detail?: string;
            /** Errors */
            errors?: {
                /** Field */
                field: string;
                /** Message */
                message: string;
            }[];
            /** Request Id */
            request_id?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** Reaction */
        Reaction: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * By
             * @enum {string}
             */
            by: "customer" | "business";
            /** Emoji */
            emoji: string;
        };
        /** ReplyWindow */
        ReplyWindow: {
            /** Closes At */
            closes_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "open" | "human_agent" | "template_only" | "closed";
        };
        /** SandboxInbound */
        SandboxInbound: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** From Id */
            from_id?: string | null;
            /** From Username */
            from_username?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dm" | "comment";
            /** Text */
            text: string;
        };
        /** SandboxInboundResult */
        SandboxInboundResult: {
            /** Stored */
            stored: number;
        };
        /** ScheduledContact */
        ScheduledContact: {
            /** Display Name */
            display_name?: string | null;
            /** Profile Picture Url */
            profile_picture_url?: string | null;
            /** Username */
            username?: string | null;
        };
        /** ScheduledMessage */
        ScheduledMessage: {
            /** Attachment Asset Ids */
            attachment_asset_ids: string[];
            contact: components["schemas"]["ScheduledContact"];
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            error?: components["schemas"]["ErrorInfo"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "instagram" | "whatsapp";
            /**
             * Send At
             * Format: date-time
             */
            send_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "sending" | "sent" | "failed" | "canceled" | "expired";
            /** Text */
            text: string;
        };
        /** ScheduledMessageCreate */
        ScheduledMessageCreate: {
            /** Attachment Asset Ids */
            attachment_asset_ids?: string[];
            /**
             * Send At
             * Format: date-time
             */
            send_at: string;
            /** Text */
            text: string;
        };
        /** ScheduledMessageList */
        ScheduledMessageList: {
            /** Items */
            items: components["schemas"]["ScheduledMessage"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ScheduledMessagePatch */
        ScheduledMessagePatch: {
            /** Send At */
            send_at?: string | null;
            /** Text */
            text?: string | null;
        };
        /**
         * SendMessage
         * @description POST …/conversations/{id}/messages with an Idempotency-Key header (TR-API-05).
         */
        SendMessage: {
            /** Attachment Asset Ids */
            attachment_asset_ids?: string[];
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Suggestion Id */
            suggestion_id?: string | null;
            template?: components["schemas"]["TemplateSend"] | null;
            /** Text */
            text?: string | null;
        };
        /** SocialAccountList */
        SocialAccountList: {
            /** Items */
            items: components["schemas"]["SocialAccountOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * SocialAccountOut
         * @description Never the token itself (SEC-02).
         */
        SocialAccountOut: {
            /** Ai Analysis Enabled */
            ai_analysis_enabled: boolean;
            /**
             * Ai Mode
             * @enum {string}
             */
            ai_mode: "off" | "suggest" | "auto";
            /** Auto Hide Spam */
            auto_hide_spam: boolean;
            /** Capabilities */
            capabilities: ("dm_send" | "dm_attachments" | "read_receipts" | "human_agent" | "templates" | "conversation_backfill" | "comments" | "private_reply" | "publish" | "post_insights" | "account_insights")[];
            /** Connected At */
            connected_at?: string | null;
            /** Display Name */
            display_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Error */
            last_error?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /**
             * Platform
             * @enum {string}
             */
            platform: "instagram" | "whatsapp";
            /** Profile Picture Url */
            profile_picture_url?: string | null;
            /**
             * Sandbox
             * @default false
             */
            sandbox: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "needs_reconnect" | "disconnected" | "error";
            /** Token Expires At */
            token_expires_at?: string | null;
            /** Username */
            username?: string | null;
        };
        /** SocialAccountPatch */
        SocialAccountPatch: {
            /** Ai Analysis Enabled */
            ai_analysis_enabled?: boolean | null;
            /** Ai Mode */
            ai_mode?: ("off" | "suggest" | "auto") | null;
            /** Auto Hide Spam */
            auto_hide_spam?: boolean | null;
            /** Display Name */
            display_name?: string | null;
        };
        /** Suggestion */
        Suggestion: {
            /** Can Answer */
            can_answer: boolean;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Low Confidence */
            low_confidence: boolean;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Missing Info */
            missing_info?: string | null;
            /** Regenerations Left */
            regenerations_left: number;
            /** Reply Text */
            reply_text?: string | null;
            /** Sources */
            sources: components["schemas"]["SuggestionSource"][];
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "sent" | "edited_sent" | "dismissed" | "superseded" | "expired" | "failed";
        };
        /** SuggestionSource */
        SuggestionSource: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
        };
        /** TemplateInfo */
        TemplateInfo: {
            /** Language */
            language: string;
            /** Name */
            name: string;
            /** Params */
            params: string[];
        };
        /** TemplateSend */
        TemplateSend: {
            /** Language */
            language: string;
            /** Name */
            name: string;
            /** Params */
            params?: string[];
        };
        /** UploadSignature */
        UploadSignature: {
            /** Api Key */
            api_key: string;
            /** Cloud Name */
            cloud_name: string;
            /** Folder */
            folder: string;
            /** Signature */
            signature: string;
            /** Timestamp */
            timestamp: number;
            /** Upload Url */
            upload_url: string;
        };
        /** UploadSignatureRequest */
        UploadSignatureRequest: {
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "post" | "message" | "knowledge";
            /**
             * Resource Type
             * @enum {string}
             */
            resource_type: "image" | "video" | "raw";
        };
        /** WhatsAppTemplate */
        WhatsAppTemplate: {
            /** Body */
            body: string;
            /**
             * Category
             * @enum {string}
             */
            category: "marketing" | "utility" | "authentication";
            /** Language */
            language: string;
            /** Name */
            name: string;
            /** Param Count */
            param_count: number;
            /** Status */
            status: string;
        };
        /** WhatsAppTemplateList */
        WhatsAppTemplateList: {
            /** Items */
            items: components["schemas"]["WhatsAppTemplate"][];
        };
        /** WorkspaceList */
        WorkspaceList: {
            /** Items */
            items: components["schemas"]["WorkspaceSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /** Automation Disclosure */
            automation_disclosure?: string | null;
            /** Checklist Dismissed At */
            checklist_dismissed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "pro" | "max";
            /** Reply Language */
            reply_language: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "agent";
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "deleting";
            /** Timezone */
            timezone: string;
        };
        /** WorkspacePatch */
        WorkspacePatch: {
            /** Automation Disclosure */
            automation_disclosure?: string | null;
            /** Checklist Dismissed */
            checklist_dismissed?: boolean | null;
            /** Name */
            name?: string | null;
            /** Reply Language */
            reply_language?: string | null;
            /** Slug */
            slug?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "pro" | "max";
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "agent";
            /** Slug */
            slug: string;
            /** Timezone */
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_data_deletion_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataDeletionStatus"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspacePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_conversations: {
        parameters: {
            query?: {
                view?: "all" | "unread" | "needs_reply" | "leads" | "ai_handled" | "archived";
                platform?: ("instagram" | "whatsapp") | null;
                account_id?: string | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_inbox_counts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxCounts"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_messages: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    send_message: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                conversation_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    mark_conversation_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_conversation_scheduled_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledMessageList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_scheduled_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledMessage"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    mark_conversation_unread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_sandbox_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    sandbox_inbound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxInbound"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxInboundResult"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stream_events: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    register_media_asset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaAssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_upload_signature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSignatureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSignature"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    retry_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_notifications: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    mark_notifications_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkRead"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_overview: {
        parameters: {
            query?: {
                range?: "7d" | "30d";
            };
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_scheduled_messages: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledMessageList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancel_scheduled_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduled_message_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_scheduled_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduled_message_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledMessagePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledMessage"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_social_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    start_instagram_connect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectStart"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    complete_whatsapp_signup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbeddedSignup"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    disconnect_social_account: {
        parameters: {
            query?: {
                delete_data?: boolean;
            };
            header?: never;
            path: {
                account_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_social_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialAccountPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resubscribe_social_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_whatsapp_templates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppTemplateList"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceList"];
                };
            };
            /** @description Problem details (application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
