"""Connections, notifications and data deletion requests (T2.2, T2.6, T2.7; §5.4, §5.9)

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-28 15:45:42.835559+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_deletion_requests",
        sa.Column("confirmation_code", sa.Text(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("platform_user_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'received'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('received', 'processing', 'completed')",
            name=op.f("ck_data_deletion_requests_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_deletion_requests")),
        sa.UniqueConstraint(
            "confirmation_code", name=op.f("uq_data_deletion_requests_confirmation_code")
        ),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), server_default=sa.text("'info'"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column(
            "channels",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{in_app}'"),
            nullable=False,
        ),
        sa.Column("dedupe_key", sa.Text(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("emailed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')", name=op.f("ck_notifications_severity")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_notifications_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_id_created_at",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_workspace_id"), "notifications", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_notifications_user_id_dedupe_key",
        "notifications",
        ["user_id", "dedupe_key"],
        unique=True,
        postgresql_where=sa.text("dedupe_key IS NOT NULL"),
    )
    op.create_table(
        "social_accounts",
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("platform_account_id", sa.Text(), nullable=False),
        sa.Column("app_scoped_id", sa.Text(), nullable=True),
        sa.Column("waba_id", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("profile_picture_url", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("access_token_enc", sa.LargeBinary(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scopes", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("ai_mode", sa.Text(), server_default=sa.text("'suggest'"), nullable=False),
        sa.Column(
            "ai_analysis_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("auto_hide_spam", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("webhooks_subscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("media_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("backfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "ai_mode IN ('off', 'suggest', 'auto')", name=op.f("ck_social_accounts_ai_mode")
        ),
        sa.CheckConstraint(
            "platform IN ('instagram', 'whatsapp', 'facebook', 'linkedin')",
            name=op.f("ck_social_accounts_platform"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'needs_reconnect', 'disconnected', 'error')",
            name=op.f("ck_social_accounts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["connected_by_user_id"],
            ["users.id"],
            name=op.f("fk_social_accounts_connected_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_social_accounts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_accounts")),
        sa.UniqueConstraint(
            "workspace_id",
            "platform",
            "platform_account_id",
            name=op.f("uq_social_accounts_workspace_id_platform_platform_account_id"),
        ),
    )
    op.create_index(
        "ix_social_accounts_platform_platform_account_id",
        "social_accounts",
        ["platform", "platform_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_social_accounts_workspace_id"), "social_accounts", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_social_accounts_live_platform_account",
        "social_accounts",
        ["platform", "platform_account_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'disconnected'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_social_accounts_live_platform_account",
        table_name="social_accounts",
        postgresql_where=sa.text("status <> 'disconnected'"),
    )
    op.drop_index(op.f("ix_social_accounts_workspace_id"), table_name="social_accounts")
    op.drop_index("ix_social_accounts_platform_platform_account_id", table_name="social_accounts")
    op.drop_table("social_accounts")
    op.drop_index(
        "uq_notifications_user_id_dedupe_key",
        table_name="notifications",
        postgresql_where=sa.text("dedupe_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_notifications_workspace_id"), table_name="notifications")
    op.drop_index("ix_notifications_user_id_created_at", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("data_deletion_requests")
    # ### end Alembic commands ###
