"""Inbox: contacts, conversations, messages, scheduled messages, media assets and items (T3.1; §5.4)

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-28
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("public_id", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("secure_url", sa.Text(), nullable=True),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.REAL(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "public_id LIKE ('ws/' || workspace_id::text || '/%%')",
            name=op.f("ck_media_assets_folder"),
        ),
        sa.CheckConstraint(
            "purpose IN ('post', 'message', 'knowledge', 'inbound')",
            name=op.f("ck_media_assets_purpose"),
        ),
        sa.CheckConstraint(
            "resource_type IN ('image', 'video', 'raw')", name=op.f("ck_media_assets_resource_type")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_media_assets_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_media_assets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("public_id", name=op.f("uq_media_assets_public_id")),
    )
    op.create_index(
        op.f("ix_media_assets_workspace_id"), "media_assets", ["workspace_id"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("platform_user_id", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("profile_picture_url", sa.Text(), nullable=True),
        sa.Column("profile_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_contacts_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_contacts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint(
            "social_account_id",
            "platform_user_id",
            name=op.f("uq_contacts_social_account_id_platform_user_id"),
        ),
    )
    op.create_index(
        "ix_contacts_search_trgm",
        "contacts",
        [
            sa.literal_column(
                "(coalesce(display_name, '') || ' ' || coalesce(username, '')) gin_trgm_ops"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_contacts_workspace_id"), "contacts", ["workspace_id"], unique=False)
    op.create_table(
        "media_items",
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("platform_media_id", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("media_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("permalink", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("comments_count", sa.Integer(), nullable=True),
        sa.Column(
            "comment_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("topics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "comments_since_summary", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("published_target_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "media_type IN ('image', 'video', 'carousel', 'reel', 'story')",
            name=op.f("ck_media_items_media_type"),
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_media_items_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_media_items_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_items")),
        sa.UniqueConstraint(
            "social_account_id",
            "platform_media_id",
            name=op.f("uq_media_items_social_account_id_platform_media_id"),
        ),
    )
    op.create_index(
        op.f("ix_media_items_workspace_id"), "media_items", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_media_items_workspace_posted",
        "media_items",
        ["workspace_id", sa.literal_column("posted_at DESC")],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_inbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_outbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_preview", sa.Text(), nullable=True),
        sa.Column("last_message_direction", sa.Text(), nullable=True),
        sa.Column("last_message_source", sa.Text(), nullable=True),
        sa.Column("last_message_kind", sa.Text(), nullable=True),
        sa.Column("unread_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("awaiting_reply", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("needs_human", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("needs_human_reason", sa.Text(), nullable=True),
        sa.Column("ai_mode_override", sa.Text(), nullable=True),
        sa.Column("ai_paused_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_intent", sa.Text(), nullable=True),
        sa.Column("last_sentiment", sa.Text(), nullable=True),
        sa.Column("priority", sa.Text(), nullable=True),
        sa.Column("lead_score", sa.SmallInteger(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_next_step", sa.Text(), nullable=True),
        sa.Column("summary_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "messages_since_summary", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("platform_conversation_id", sa.Text(), nullable=True),
        sa.Column("window_reminder_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "ai_mode_override IS NULL OR ai_mode_override IN ('off', 'suggest', 'auto')",
            name=op.f("ck_conversations_ai_mode_override"),
        ),
        sa.CheckConstraint("status IN ('open', 'archived')", name=op.f("ck_conversations_status")),
        sa.CheckConstraint(
            "last_message_preview IS NULL OR char_length(last_message_preview) <= 200",
            name=op.f("ck_conversations_preview_length"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_conversations_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_conversations_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_conversations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "social_account_id",
            "contact_id",
            name=op.f("uq_conversations_social_account_id_contact_id"),
        ),
    )
    op.create_index(
        "ix_conversations_awaiting_reply",
        "conversations",
        ["workspace_id", sa.literal_column("last_message_at DESC")],
        unique=False,
        postgresql_where=sa.text("awaiting_reply"),
    )
    op.create_index(
        "ix_conversations_leads",
        "conversations",
        ["workspace_id", sa.literal_column("last_message_at DESC")],
        unique=False,
        postgresql_where=sa.text("lead_score >= 60"),
    )
    op.create_index(
        "ix_conversations_list",
        "conversations",
        [
            "workspace_id",
            "status",
            sa.literal_column("last_message_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "ix_conversations_needs_human",
        "conversations",
        ["workspace_id", sa.literal_column("last_message_at DESC")],
        unique=False,
        postgresql_where=sa.text("needs_human"),
    )
    op.create_index(
        "ix_conversations_unread",
        "conversations",
        ["workspace_id", sa.literal_column("last_message_at DESC")],
        unique=False,
        postgresql_where=sa.text("unread_count > 0"),
    )
    op.create_index(
        op.f("ix_conversations_workspace_id"), "conversations", ["workspace_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), server_default=sa.text("'text'"), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attachments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("template", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("platform_message_id", sa.Text(), nullable=True),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("human_agent_tag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sent_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("suggestion_id", sa.Uuid(), nullable=True),
        sa.Column("automation_run_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "automation_handled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("reply_to_platform_message_id", sa.Text(), nullable=True),
        sa.Column(
            "reactions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', coalesce(text, ''))", persisted=True),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "direction IN ('inbound', 'outbound', 'system')", name=op.f("ck_messages_direction")
        ),
        sa.CheckConstraint(
            "kind IN ('text', 'image', 'video', 'audio', 'file', 'sticker', 'story_mention', 'story_reply', 'share', 'template', 'location', 'unsupported', 'system')",
            name=op.f("ck_messages_kind"),
        ),
        sa.CheckConstraint(
            "source IN ('customer', 'human', 'ai_auto', 'automation', 'native_app', 'system')",
            name=op.f("ck_messages_source"),
        ),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('received', 'queued', 'sending', 'sent', 'delivered', 'read', 'failed')",
            name=op.f("ck_messages_status"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sent_by_user_id"],
            ["users.id"],
            name=op.f("fk_messages_sent_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_messages_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_messages_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id", "client_id", name=op.f("uq_messages_conversation_id_client_id")
        ),
        sa.UniqueConstraint(
            "social_account_id",
            "platform_message_id",
            name=op.f("uq_messages_social_account_id_platform_message_id"),
        ),
    )
    op.create_index(
        "ix_messages_in_flight",
        "messages",
        ["status", "updated_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'sending')"),
    )
    op.create_index(
        "ix_messages_search_tsv", "messages", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_messages_thread",
        "messages",
        ["conversation_id", sa.literal_column("occurred_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_messages_workspace_id"), "messages", ["workspace_id"], unique=False)
    op.create_table(
        "scheduled_messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "attachment_asset_ids",
            postgresql.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("send_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'scheduled'"), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('scheduled', 'sending', 'sent', 'failed', 'canceled', 'expired')",
            name=op.f("ck_scheduled_messages_status"),
        ),
        sa.CheckConstraint(
            "char_length(text) BETWEEN 1 AND 2000", name=op.f("ck_scheduled_messages_text_length")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_scheduled_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_scheduled_messages_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_scheduled_messages_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_scheduled_messages_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_messages")),
    )
    op.create_index(
        "ix_scheduled_messages_due",
        "scheduled_messages",
        ["send_at"],
        unique=False,
        postgresql_where=sa.text("status = 'scheduled'"),
    )
    op.create_index(
        op.f("ix_scheduled_messages_workspace_id"),
        "scheduled_messages",
        ["workspace_id"],
        unique=False,
    )
    # messages and scheduled_messages reference each other; add this one once both exist.
    op.create_foreign_key(
        op.f("fk_messages_scheduled_message_id_scheduled_messages"),
        "messages",
        "scheduled_messages",
        ["scheduled_message_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_scheduled_message_id_scheduled_messages"), "messages", type_="foreignkey"
    )
    op.drop_index(op.f("ix_scheduled_messages_workspace_id"), table_name="scheduled_messages")
    op.drop_index(
        "ix_scheduled_messages_due",
        table_name="scheduled_messages",
        postgresql_where=sa.text("status = 'scheduled'"),
    )
    op.drop_table("scheduled_messages")
    op.drop_index(op.f("ix_messages_workspace_id"), table_name="messages")
    op.drop_index("ix_messages_thread", table_name="messages")
    op.drop_index("ix_messages_search_tsv", table_name="messages", postgresql_using="gin")
    op.drop_index(
        "ix_messages_in_flight",
        table_name="messages",
        postgresql_where=sa.text("status IN ('queued', 'sending')"),
    )
    op.drop_table("messages")
    op.drop_index(op.f("ix_conversations_workspace_id"), table_name="conversations")
    op.drop_index(
        "ix_conversations_unread",
        table_name="conversations",
        postgresql_where=sa.text("unread_count > 0"),
    )
    op.drop_index(
        "ix_conversations_needs_human",
        table_name="conversations",
        postgresql_where=sa.text("needs_human"),
    )
    op.drop_index("ix_conversations_list", table_name="conversations")
    op.drop_index(
        "ix_conversations_leads",
        table_name="conversations",
        postgresql_where=sa.text("lead_score >= 60"),
    )
    op.drop_index(
        "ix_conversations_awaiting_reply",
        table_name="conversations",
        postgresql_where=sa.text("awaiting_reply"),
    )
    op.drop_table("conversations")
    op.drop_index("ix_media_items_workspace_posted", table_name="media_items")
    op.drop_index(op.f("ix_media_items_workspace_id"), table_name="media_items")
    op.drop_table("media_items")
    op.drop_index(op.f("ix_contacts_workspace_id"), table_name="contacts")
    op.drop_index("ix_contacts_search_trgm", table_name="contacts", postgresql_using="gin")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_media_assets_workspace_id"), table_name="media_assets")
    op.drop_table("media_assets")
    # ### end Alembic commands ###
