"""Automations, keywords, posts and runs; comments (T4.1; §5.6)

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "messages",
        sa.Column(
            "buttons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automations",
        sa.Column("social_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "name", sa.Text(), server_default=sa.text("'Untitled automation'"), nullable=False
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=True),
        sa.Column("match_mode", sa.Text(), server_default=sa.text("'word'"), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("ai_instructions", sa.Text(), nullable=True),
        sa.Column(
            "public_reply_texts",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "message_buttons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("message_media_asset_id", sa.Uuid(), nullable=True),
        sa.Column("template_key", sa.Text(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "surge_order", sa.Text(), server_default=sa.text("'oldest_first'"), nullable=False
        ),
        sa.Column("post_scope", sa.Text(), server_default=sa.text("'all'"), nullable=False),
        sa.Column(
            "cooldown_hours", sa.SmallInteger(), server_default=sa.text("24"), nullable=False
        ),
        sa.Column("priority", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "action IS NULL OR action IN ('send_message', 'ai_reply')",
            name=op.f("ck_automations_action"),
        ),
        sa.CheckConstraint(
            "match_mode IN ('word', 'exact', 'contains')", name=op.f("ck_automations_match_mode")
        ),
        sa.CheckConstraint(
            "post_scope IN ('all', 'selected', 'next_post')", name=op.f("ck_automations_post_scope")
        ),
        sa.CheckConstraint(
            "status <> 'active' OR (social_account_id IS NOT NULL AND trigger IS NOT NULL AND action IS NOT NULL)",
            name=op.f("ck_automations_complete_when_active"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'paused')", name=op.f("ck_automations_status")
        ),
        sa.CheckConstraint(
            "surge_order IN ('oldest_first', 'newest_first', 'public_only')",
            name=op.f("ck_automations_surge_order"),
        ),
        sa.CheckConstraint(
            "trigger IS NULL OR trigger IN ('dm_keyword', 'comment_keyword', 'comment_any')",
            name=op.f("ck_automations_trigger"),
        ),
        sa.CheckConstraint(
            "ai_instructions IS NULL OR char_length(ai_instructions) <= 2000",
            name=op.f("ck_automations_ai_instructions_length"),
        ),
        sa.CheckConstraint(
            "cardinality(public_reply_texts) <= 5", name=op.f("ck_automations_public_reply_texts")
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 80", name=op.f("ck_automations_name_length")
        ),
        sa.CheckConstraint(
            "cooldown_hours BETWEEN 0 AND 72", name=op.f("ck_automations_cooldown_hours")
        ),
        sa.CheckConstraint(
            "jsonb_array_length(message_buttons) <= 3", name=op.f("ck_automations_message_buttons")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_automations_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_automations_message_media_asset_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_automations_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_automations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automations")),
    )
    op.create_index(
        "ix_automations_runtime",
        "automations",
        ["social_account_id", "trigger", "status", "priority", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automations_workspace_id"), "automations", ["workspace_id"], unique=False
    )
    op.create_table(
        "automation_keywords",
        sa.Column("automation_id", sa.Uuid(), nullable=False),
        sa.Column("keyword", sa.Text(), nullable=False),
        sa.Column("keyword_normalized", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "char_length(keyword) BETWEEN 1 AND 100",
            name=op.f("ck_automation_keywords_keyword_length"),
        ),
        sa.ForeignKeyConstraint(
            ["automation_id"],
            ["automations.id"],
            name=op.f("fk_automation_keywords_automation_id_automations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_automation_keywords_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_keywords")),
        sa.UniqueConstraint(
            "automation_id",
            "keyword_normalized",
            name=op.f("uq_automation_keywords_automation_id_keyword_normalized"),
        ),
    )
    op.create_index(
        op.f("ix_automation_keywords_workspace_id"),
        "automation_keywords",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "automation_posts",
        sa.Column("automation_id", sa.Uuid(), nullable=False),
        sa.Column("media_item_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_post_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "media_item_id IS NOT NULL OR scheduled_post_id IS NOT NULL",
            name=op.f("ck_automation_posts_has_target"),
        ),
        sa.ForeignKeyConstraint(
            ["automation_id"],
            ["automations.id"],
            name=op.f("fk_automation_posts_automation_id_automations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_item_id"],
            ["media_items.id"],
            name=op.f("fk_automation_posts_media_item_id_media_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_automation_posts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_posts")),
    )
    op.create_index(
        op.f("ix_automation_posts_workspace_id"), "automation_posts", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_automation_posts_media_item",
        "automation_posts",
        ["automation_id", "media_item_id"],
        unique=True,
        postgresql_where=sa.text("media_item_id IS NOT NULL"),
    )
    op.create_index(
        "uq_automation_posts_scheduled_post",
        "automation_posts",
        ["automation_id", "scheduled_post_id"],
        unique=True,
        postgresql_where=sa.text("scheduled_post_id IS NOT NULL"),
    )
    op.create_table(
        "comments",
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("media_item_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("platform_comment_id", sa.Text(), nullable=False),
        sa.Column("parent_platform_comment_id", sa.Text(), nullable=True),
        sa.Column("author_platform_user_id", sa.Text(), nullable=True),
        sa.Column("author_username", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("like_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("commented_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "analysis_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("our_reply_platform_id", sa.Text(), nullable=True),
        sa.Column("our_reply_text", sa.Text(), nullable=True),
        sa.Column("our_replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("private_reply_message_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "analysis_status IN ('pending', 'done', 'skipped')",
            name=op.f("ck_comments_analysis_status"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_comments_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["media_item_id"],
            ["media_items.id"],
            name=op.f("fk_comments_media_item_id_media_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["private_reply_message_id"],
            ["messages.id"],
            name=op.f("fk_comments_private_reply_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_comments_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_comments_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
        sa.UniqueConstraint(
            "social_account_id",
            "platform_comment_id",
            name=op.f("uq_comments_social_account_id_platform_comment_id"),
        ),
    )
    op.create_index(
        "ix_comments_media_commented",
        "comments",
        ["media_item_id", sa.literal_column("commented_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_comments_pending_analysis",
        "comments",
        ["social_account_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("analysis_status = 'pending'"),
    )
    op.create_index(op.f("ix_comments_workspace_id"), "comments", ["workspace_id"], unique=False)
    op.create_table(
        "automation_runs",
        sa.Column("automation_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("trigger_message_id", sa.Uuid(), nullable=True),
        sa.Column("trigger_comment_id", sa.Uuid(), nullable=True),
        sa.Column("matched_keyword", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("private_reply_message_id", sa.Uuid(), nullable=True),
        sa.Column("public_reply_platform_id", sa.Text(), nullable=True),
        sa.Column("public_reply_variant", sa.SmallInteger(), nullable=True),
        sa.Column("contact_replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "result IN ('queued', 'sent', 'partial', 'failed', 'skipped_cooldown', 'skipped_expired', 'escalated')",
            name=op.f("ck_automation_runs_result"),
        ),
        sa.CheckConstraint(
            "(trigger_message_id IS NULL) <> (trigger_comment_id IS NULL)",
            name=op.f("ck_automation_runs_one_trigger"),
        ),
        sa.ForeignKeyConstraint(
            ["automation_id"],
            ["automations.id"],
            name=op.f("fk_automation_runs_automation_id_automations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_automation_runs_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_automation_runs_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["private_reply_message_id"],
            ["messages.id"],
            name=op.f("fk_automation_runs_private_reply_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trigger_comment_id"],
            ["comments.id"],
            name=op.f("fk_automation_runs_trigger_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trigger_message_id"],
            ["messages.id"],
            name=op.f("fk_automation_runs_trigger_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_automation_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_runs")),
    )
    op.create_index(
        "ix_automation_runs_cooldown",
        "automation_runs",
        ["automation_id", "contact_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_automation_runs_queued",
        "automation_runs",
        ["automation_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("result = 'queued'"),
    )
    op.create_index(
        "ix_automation_runs_recent",
        "automation_runs",
        ["automation_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_runs_workspace_id"), "automation_runs", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_automation_runs_comment",
        "automation_runs",
        ["automation_id", "trigger_comment_id"],
        unique=True,
        postgresql_where=sa.text("trigger_comment_id IS NOT NULL"),
    )
    op.create_index(
        "uq_automation_runs_message",
        "automation_runs",
        ["automation_id", "trigger_message_id"],
        unique=True,
        postgresql_where=sa.text("trigger_message_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_messages_automation_run_id_automation_runs"),
        "messages",
        "automation_runs",
        ["automation_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("messages", "buttons")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_automation_run_id_automation_runs"), "messages", type_="foreignkey"
    )
    op.drop_index(
        "uq_automation_runs_message",
        table_name="automation_runs",
        postgresql_where=sa.text("trigger_message_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_automation_runs_comment",
        table_name="automation_runs",
        postgresql_where=sa.text("trigger_comment_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_automation_runs_workspace_id"), table_name="automation_runs")
    op.drop_index("ix_automation_runs_recent", table_name="automation_runs")
    op.drop_index(
        "ix_automation_runs_queued",
        table_name="automation_runs",
        postgresql_where=sa.text("result = 'queued'"),
    )
    op.drop_index("ix_automation_runs_cooldown", table_name="automation_runs")
    op.drop_table("automation_runs")
    op.drop_index(op.f("ix_comments_workspace_id"), table_name="comments")
    op.drop_index(
        "ix_comments_pending_analysis",
        table_name="comments",
        postgresql_where=sa.text("analysis_status = 'pending'"),
    )
    op.drop_index("ix_comments_media_commented", table_name="comments")
    op.drop_table("comments")
    op.drop_index(
        "uq_automation_posts_scheduled_post",
        table_name="automation_posts",
        postgresql_where=sa.text("scheduled_post_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_automation_posts_media_item",
        table_name="automation_posts",
        postgresql_where=sa.text("media_item_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_automation_posts_workspace_id"), table_name="automation_posts")
    op.drop_table("automation_posts")
    op.drop_index(op.f("ix_automation_keywords_workspace_id"), table_name="automation_keywords")
    op.drop_table("automation_keywords")
    op.drop_index(op.f("ix_automations_workspace_id"), table_name="automations")
    op.drop_index("ix_automations_runtime", table_name="automations")
    op.drop_table("automations")
    # ### end Alembic commands ###
