"""Tap first (FR-AUT-21) and the follow nudge (FR-AUT-22): automation settings, run fields,
the contact's follow status, quick replies on messages

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-29 04:51:01.405235+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "automation_runs", sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("automation_runs", sa.Column("follows_business", sa.Boolean(), nullable=True))
    op.add_column("automation_runs", sa.Column("nudge_message_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_automation_runs_awaiting",
        "automation_runs",
        ["contact_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("result = 'awaiting_reply'"),
    )
    op.create_foreign_key(
        op.f("fk_automation_runs_nudge_message_id_messages"),
        "automation_runs",
        "messages",
        ["nudge_message_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "automations",
        sa.Column("confirm_first", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("automations", sa.Column("opening_text", sa.Text(), nullable=True))
    op.add_column("automations", sa.Column("opening_button", sa.Text(), nullable=True))
    op.add_column(
        "automations",
        sa.Column("follow_nudge", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("automations", sa.Column("follow_nudge_text", sa.Text(), nullable=True))
    op.add_column("contacts", sa.Column("follows_business", sa.Boolean(), nullable=True))
    op.add_column(
        "contacts", sa.Column("follows_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "messages",
        sa.Column(
            "quick_replies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("messages", sa.Column("quick_reply_payload", sa.Text(), nullable=True))
    op.create_check_constraint(
        op.f("ck_automations_opening_button_length"),
        "automations",
        "opening_button IS NULL OR char_length(opening_button) <= 20",
    )
    op.create_check_constraint(
        op.f("ck_automations_follow_nudge_text_length"),
        "automations",
        "follow_nudge_text IS NULL OR char_length(follow_nudge_text) <= 300",
    )
    op.drop_constraint(op.f("ck_automation_runs_result"), "automation_runs", type_="check")
    op.create_check_constraint(
        op.f("ck_automation_runs_result"),
        "automation_runs",
        "result IN ('queued', 'sent', 'partial', 'failed', 'skipped_cooldown', 'skipped_expired', 'escalated', 'awaiting_reply')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("UPDATE automation_runs SET result = 'sent' WHERE result = 'awaiting_reply'")
    op.drop_constraint(op.f("ck_automation_runs_result"), "automation_runs", type_="check")
    op.create_check_constraint(
        op.f("ck_automation_runs_result"),
        "automation_runs",
        "result IN ('queued', 'sent', 'partial', 'failed', 'skipped_cooldown', 'skipped_expired', 'escalated')",
    )
    op.drop_constraint(
        op.f("ck_automations_follow_nudge_text_length"), "automations", type_="check"
    )
    op.drop_constraint(op.f("ck_automations_opening_button_length"), "automations", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "quick_reply_payload")
    op.drop_column("messages", "quick_replies")
    op.drop_column("contacts", "follows_checked_at")
    op.drop_column("contacts", "follows_business")
    op.drop_column("automations", "follow_nudge_text")
    op.drop_column("automations", "follow_nudge")
    op.drop_column("automations", "opening_button")
    op.drop_column("automations", "opening_text")
    op.drop_column("automations", "confirm_first")
    op.drop_constraint(
        op.f("fk_automation_runs_nudge_message_id_messages"), "automation_runs", type_="foreignkey"
    )
    op.drop_index(
        "ix_automation_runs_awaiting",
        table_name="automation_runs",
        postgresql_where=sa.text("result = 'awaiting_reply'"),
    )
    op.drop_column("automation_runs", "nudge_message_id")
    op.drop_column("automation_runs", "follows_business")
    op.drop_column("automation_runs", "confirmed_at")
    # ### end Alembic commands ###
