"""AI and knowledge (§5.5, §5.8): message analyses, reply suggestions, knowledge sources and chunks
(pgvector, HNSW), knowledge gaps (trigram), auto-reply decisions, AI usage events; messages.suggestion_id

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-29 07:11:08.928611+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage_events",
        sa.Column("feature", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("credits", sa.SmallInteger(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("ref_type", sa.Text(), nullable=True),
        sa.Column("ref_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "feature IN ('message_analysis', 'reply_suggestion', 'auto_reply', 'conversation_summary', 'comment_analysis', 'post_summary', 'caption_generation', 'knowledge_test', 'automation_ai_reply')",
            name=op.f("ck_ai_usage_events_feature"),
        ),
        sa.CheckConstraint(
            "outcome IN ('ok', 'error', 'timeout')", name=op.f("ck_ai_usage_events_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_ai_usage_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage_events")),
    )
    op.create_index(
        "ix_ai_usage_events_recent",
        "ai_usage_events",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_events_workspace_id"), "ai_usage_events", ["workspace_id"], unique=False
    )
    op.create_table(
        "knowledge_sources",
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("file_asset_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("char_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'ready', 'failed')",
            name=op.f("ck_knowledge_sources_status"),
        ),
        sa.CheckConstraint(
            "type IN ('faq', 'text', 'url', 'file')", name=op.f("ck_knowledge_sources_type")
        ),
        sa.CheckConstraint(
            "body IS NULL OR char_length(body) <= 20000",
            name=op.f("ck_knowledge_sources_body_length"),
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 120", name=op.f("ck_knowledge_sources_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_knowledge_sources_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["file_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_knowledge_sources_file_asset_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_knowledge_sources_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_sources")),
    )
    op.create_index(
        "ix_knowledge_sources_workspace",
        "knowledge_sources",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_sources_workspace_id"),
        "knowledge_sources",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(768), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge_sources.id"],
            name=op.f("fk_knowledge_chunks_source_id_knowledge_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_knowledge_chunks_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
    )
    op.create_index(
        "ix_knowledge_chunks_embedding",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_knowledge_chunks_source_id"), "knowledge_chunks", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_workspace_id"), "knowledge_chunks", ["workspace_id"], unique=False
    )
    op.create_table(
        "knowledge_gaps",
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("topic_normalized", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("occurrences", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "example_message_ids",
            postgresql.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("resolved_source_id", sa.Uuid(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'answered', 'dismissed')", name=op.f("ck_knowledge_gaps_status")
        ),
        sa.CheckConstraint(
            "cardinality(example_message_ids) <= 5", name=op.f("ck_knowledge_gaps_examples")
        ),
        sa.ForeignKeyConstraint(
            ["resolved_source_id"],
            ["knowledge_sources.id"],
            name=op.f("fk_knowledge_gaps_resolved_source_id_knowledge_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_knowledge_gaps_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_gaps")),
    )
    op.create_index(
        "ix_knowledge_gaps_list",
        "knowledge_gaps",
        ["workspace_id", "status", sa.literal_column("occurrences DESC")],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_gaps_topic_trgm",
        "knowledge_gaps",
        ["topic_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"topic_normalized": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_knowledge_gaps_workspace_id"), "knowledge_gaps", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_knowledge_gaps_open_topic",
        "knowledge_gaps",
        ["workspace_id", "topic_normalized"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "message_analyses",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("sentiment", sa.Text(), nullable=False),
        sa.Column("sentiment_score", sa.REAL(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("lead_score", sa.SmallInteger(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column(
            "topics", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("needs_reply", sa.Boolean(), nullable=False),
        sa.Column("needs_human", sa.Boolean(), nullable=False),
        sa.Column("needs_human_reason", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("corrected_intent", sa.Text(), nullable=True),
        sa.Column("corrected_sentiment", sa.Text(), nullable=True),
        sa.Column("corrected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "corrected_intent IS NULL OR corrected_intent IN ('pricing', 'product_inquiry', 'purchase', 'order_status', 'shipping', 'support', 'complaint', 'refund', 'feedback', 'collaboration', 'greeting', 'spam', 'other')",
            name=op.f("ck_message_analyses_corrected_intent"),
        ),
        sa.CheckConstraint(
            "corrected_sentiment IS NULL OR corrected_sentiment IN ('positive', 'neutral', 'negative')",
            name=op.f("ck_message_analyses_corrected_sentiment"),
        ),
        sa.CheckConstraint(
            "intent IN ('pricing', 'product_inquiry', 'purchase', 'order_status', 'shipping', 'support', 'complaint', 'refund', 'feedback', 'collaboration', 'greeting', 'spam', 'other')",
            name=op.f("ck_message_analyses_intent"),
        ),
        sa.CheckConstraint(
            "needs_human_reason IS NULL OR needs_human_reason IN ('refund', 'legal', 'complaint', 'negative_sentiment', 'abuse', 'account_or_payment', 'human_requested', 'low_confidence', 'out_of_knowledge', 'window_closed', 'policy_keyword', 'output_blocked')",
            name=op.f("ck_message_analyses_needs_human_reason"),
        ),
        sa.CheckConstraint(
            "priority IN ('critical', 'high', 'medium', 'low')",
            name=op.f("ck_message_analyses_priority"),
        ),
        sa.CheckConstraint(
            "sentiment IN ('positive', 'neutral', 'negative')",
            name=op.f("ck_message_analyses_sentiment"),
        ),
        sa.CheckConstraint("cardinality(topics) <= 3", name=op.f("ck_message_analyses_topics")),
        sa.CheckConstraint(
            "lead_score BETWEEN 0 AND 100", name=op.f("ck_message_analyses_lead_score")
        ),
        sa.CheckConstraint(
            "sentiment_score BETWEEN -1 AND 1", name=op.f("ck_message_analyses_sentiment_score")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_message_analyses_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["corrected_by_user_id"],
            ["users.id"],
            name=op.f("fk_message_analyses_corrected_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_analyses_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_message_analyses_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_analyses")),
        sa.UniqueConstraint("message_id", name=op.f("uq_message_analyses_message_id")),
    )
    op.create_index(
        "ix_message_analyses_conversation",
        "message_analyses",
        ["conversation_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_analyses_workspace_id"), "message_analyses", ["workspace_id"], unique=False
    )
    op.create_table(
        "reply_suggestions",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("can_answer", sa.Boolean(), nullable=False),
        sa.Column("reply_text", sa.Text(), nullable=True),
        sa.Column("missing_info", sa.Text(), nullable=True),
        sa.Column("missing_topic", sa.Text(), nullable=True),
        sa.Column("model_confidence", sa.REAL(), nullable=True),
        sa.Column("top_similarity", sa.REAL(), nullable=True),
        sa.Column(
            "used_chunk_ids",
            postgresql.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "regeneration_index", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("sent_message_id", sa.Uuid(), nullable=True),
        sa.Column("edit_distance", sa.REAL(), nullable=True),
        sa.Column("automation_run_id", sa.Uuid(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'edited_sent', 'dismissed', 'superseded', 'expired', 'failed')",
            name=op.f("ck_reply_suggestions_status"),
        ),
        sa.CheckConstraint(
            "regeneration_index BETWEEN 0 AND 5",
            name=op.f("ck_reply_suggestions_regeneration_index"),
        ),
        sa.ForeignKeyConstraint(
            ["automation_run_id"],
            ["automation_runs.id"],
            name=op.f("fk_reply_suggestions_automation_run_id_automation_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_reply_suggestions_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_reply_suggestions_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sent_message_id"],
            ["messages.id"],
            name=op.f("fk_reply_suggestions_sent_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_reply_suggestions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reply_suggestions")),
    )
    op.create_index(
        "ix_reply_suggestions_conversation",
        "reply_suggestions",
        ["conversation_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_reply_suggestions_workspace_id"),
        "reply_suggestions",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "uq_reply_suggestions_pending",
        "reply_suggestions",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "ai_decisions",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("suggestion_id", sa.Uuid(), nullable=True),
        sa.Column("sent_message_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_feedback", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('auto_sent', 'escalated', 'skipped')", name=op.f("ck_ai_decisions_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_ai_decisions_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_ai_decisions_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sent_message_id"],
            ["messages.id"],
            name=op.f("fk_ai_decisions_sent_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["reply_suggestions.id"],
            name=op.f("fk_ai_decisions_suggestion_id_reply_suggestions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_ai_decisions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_decisions")),
    )
    op.create_index(
        "ix_ai_decisions_conversation",
        "ai_decisions",
        ["conversation_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_decisions_message_id"), "ai_decisions", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_decisions_sent_message_id"), "ai_decisions", ["sent_message_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_decisions_workspace_id"), "ai_decisions", ["workspace_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_messages_suggestion_id_reply_suggestions"),
        "messages",
        "reply_suggestions",
        ["suggestion_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_suggestion_id_reply_suggestions"), "messages", type_="foreignkey"
    )
    op.drop_index(op.f("ix_ai_decisions_workspace_id"), table_name="ai_decisions")
    op.drop_index(op.f("ix_ai_decisions_sent_message_id"), table_name="ai_decisions")
    op.drop_index(op.f("ix_ai_decisions_message_id"), table_name="ai_decisions")
    op.drop_index("ix_ai_decisions_conversation", table_name="ai_decisions")
    op.drop_table("ai_decisions")
    op.drop_index(
        "uq_reply_suggestions_pending",
        table_name="reply_suggestions",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_reply_suggestions_workspace_id"), table_name="reply_suggestions")
    op.drop_index("ix_reply_suggestions_conversation", table_name="reply_suggestions")
    op.drop_table("reply_suggestions")
    op.drop_index(op.f("ix_message_analyses_workspace_id"), table_name="message_analyses")
    op.drop_index("ix_message_analyses_conversation", table_name="message_analyses")
    op.drop_table("message_analyses")
    op.drop_index(
        "uq_knowledge_gaps_open_topic",
        table_name="knowledge_gaps",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(op.f("ix_knowledge_gaps_workspace_id"), table_name="knowledge_gaps")
    op.drop_index(
        "ix_knowledge_gaps_topic_trgm",
        table_name="knowledge_gaps",
        postgresql_using="gin",
        postgresql_ops={"topic_normalized": "gin_trgm_ops"},
    )
    op.drop_index("ix_knowledge_gaps_list", table_name="knowledge_gaps")
    op.drop_table("knowledge_gaps")
    op.drop_index(op.f("ix_knowledge_chunks_workspace_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_source_id"), table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_embedding",
        table_name="knowledge_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_sources_workspace_id"), table_name="knowledge_sources")
    op.drop_index("ix_knowledge_sources_workspace", table_name="knowledge_sources")
    op.drop_table("knowledge_sources")
    op.drop_index(op.f("ix_ai_usage_events_workspace_id"), table_name="ai_usage_events")
    op.drop_index("ix_ai_usage_events_recent", table_name="ai_usage_events")
    op.drop_table("ai_usage_events")
    # ### end Alembic commands ###
