"""Comment intelligence and post analytics (§5.6; TR-AI-11, FR-ANL-01, TR-AGT-05): comment_analyses,
post_metric_snapshots, account_daily_metrics; indexes for an account's previous posts and comments by
date

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-29 12:18:41.421048+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_daily_metrics",
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("followers_count", sa.Integer(), nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_account_daily_metrics_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_account_daily_metrics_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_daily_metrics")),
        sa.UniqueConstraint(
            "social_account_id",
            "date",
            name=op.f("uq_account_daily_metrics_social_account_id_date"),
        ),
    )
    op.create_index(
        op.f("ix_account_daily_metrics_workspace_id"),
        "account_daily_metrics",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "post_metric_snapshots",
        sa.Column("media_item_id", sa.Uuid(), nullable=False),
        sa.Column("window", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("insights_final", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "\"window\" IN ('1h', '6h', '24h', '72h', '7d', '30d')",
            name=op.f("ck_post_metric_snapshots_window"),
        ),
        sa.ForeignKeyConstraint(
            ["media_item_id"],
            ["media_items.id"],
            name=op.f("fk_post_metric_snapshots_media_item_id_media_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_post_metric_snapshots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_metric_snapshots")),
        sa.UniqueConstraint(
            "media_item_id", "window", name=op.f("uq_post_metric_snapshots_media_item_id_window")
        ),
    )
    op.create_index(
        op.f("ix_post_metric_snapshots_workspace_id"),
        "post_metric_snapshots",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "comment_analyses",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("media_item_id", sa.Uuid(), nullable=False),
        sa.Column("sentiment", sa.Text(), nullable=False),
        sa.Column("sentiment_score", sa.REAL(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("is_spam", sa.Boolean(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "intent IN ('pricing', 'product_inquiry', 'purchase', 'order_status', 'shipping', 'support', 'complaint', 'refund', 'feedback', 'collaboration', 'greeting', 'spam', 'other')",
            name=op.f("ck_comment_analyses_intent"),
        ),
        sa.CheckConstraint(
            "sentiment IN ('positive', 'neutral', 'negative')",
            name=op.f("ck_comment_analyses_sentiment"),
        ),
        sa.CheckConstraint(
            "sentiment_score BETWEEN -1 AND 1", name=op.f("ck_comment_analyses_sentiment_score")
        ),
        sa.CheckConstraint(
            "topic IS NULL OR char_length(topic) BETWEEN 1 AND 60",
            name=op.f("ck_comment_analyses_topic_length"),
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_comment_analyses_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_item_id"],
            ["media_items.id"],
            name=op.f("fk_comment_analyses_media_item_id_media_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_comment_analyses_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_analyses")),
        sa.UniqueConstraint("comment_id", name=op.f("uq_comment_analyses_comment_id")),
    )
    op.create_index(
        "ix_comment_analyses_media_sentiment",
        "comment_analyses",
        ["media_item_id", "sentiment", "is_spam"],
        unique=False,
    )
    op.create_index(
        "ix_comment_analyses_media_topic",
        "comment_analyses",
        ["media_item_id", "topic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comment_analyses_workspace_id"), "comment_analyses", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_comments_workspace_commented",
        "comments",
        ["workspace_id", sa.literal_column("commented_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_media_items_account_posted",
        "media_items",
        ["social_account_id", sa.literal_column("posted_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_media_items_account_posted", table_name="media_items")
    op.drop_index("ix_comments_workspace_commented", table_name="comments")
    op.drop_index(op.f("ix_comment_analyses_workspace_id"), table_name="comment_analyses")
    op.drop_index("ix_comment_analyses_media_topic", table_name="comment_analyses")
    op.drop_index("ix_comment_analyses_media_sentiment", table_name="comment_analyses")
    op.drop_table("comment_analyses")
    op.drop_index(op.f("ix_post_metric_snapshots_workspace_id"), table_name="post_metric_snapshots")
    op.drop_table("post_metric_snapshots")
    op.drop_index(op.f("ix_account_daily_metrics_workspace_id"), table_name="account_daily_metrics")
    op.drop_table("account_daily_metrics")
    # ### end Alembic commands ###
