"""Publishing (§5.7; FR-PUB-01…14, F-13): scheduled_posts, scheduled_post_assets,
scheduled_post_targets, posting_slots, hashtag_groups; the foreign keys that waited for them
(automation_posts.scheduled_post_id, media_items.published_target_id)

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-29 15:18:17.059602+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashtag_groups",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("hashtags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "array_to_string(hashtags, ' ') = lower(array_to_string(hashtags, ' ')) AND strpos(array_to_string(hashtags, ' '), '#') = 0",
            name=op.f("ck_hashtag_groups_hashtags_normalized"),
        ),
        sa.CheckConstraint(
            "cardinality(hashtags) BETWEEN 1 AND 30", name=op.f("ck_hashtag_groups_hashtags_count")
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 40", name=op.f("ck_hashtag_groups_name_length")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_hashtag_groups_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hashtag_groups")),
    )
    op.create_index(
        op.f("ix_hashtag_groups_workspace_id"), "hashtag_groups", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_hashtag_groups_workspace_id_lower_name",
        "hashtag_groups",
        ["workspace_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "scheduled_posts",
        sa.Column("status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("format", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("first_comment", sa.Text(), nullable=True),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "format IS NULL OR format IN ('image', 'carousel', 'reel')",
            name=op.f("ck_scheduled_posts_format"),
        ),
        sa.CheckConstraint(
            "status = 'draft' OR (publish_at IS NOT NULL AND format IS NOT NULL)",
            name=op.f("ck_scheduled_posts_schedulable"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'scheduled', 'publishing', 'published', 'partially_published', 'failed', 'canceled')",
            name=op.f("ck_scheduled_posts_status"),
        ),
        sa.CheckConstraint(
            "char_length(caption) <= 2200", name=op.f("ck_scheduled_posts_caption_length")
        ),
        sa.CheckConstraint(
            "first_comment IS NULL OR char_length(first_comment) BETWEEN 1 AND 2200",
            name=op.f("ck_scheduled_posts_first_comment_length"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_scheduled_posts_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_scheduled_posts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_posts")),
    )
    op.create_index(
        "ix_scheduled_posts_due",
        "scheduled_posts",
        ["publish_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('scheduled', 'publishing')"),
    )
    op.create_index(
        op.f("ix_scheduled_posts_workspace_id"), "scheduled_posts", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_scheduled_posts_workspace_publish_at",
        "scheduled_posts",
        ["workspace_id", "publish_at"],
        unique=False,
    )
    op.create_table(
        "posting_slots",
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("local_time", sa.Time(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "date_trunc('minute', local_time) = local_time",
            name=op.f("ck_posting_slots_whole_minute"),
        ),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_posting_slots_weekday")),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_posting_slots_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_posting_slots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posting_slots")),
        sa.UniqueConstraint(
            "social_account_id",
            "weekday",
            "local_time",
            name=op.f("uq_posting_slots_social_account_id_weekday_local_time"),
        ),
    )
    op.create_index(
        op.f("ix_posting_slots_workspace_id"), "posting_slots", ["workspace_id"], unique=False
    )
    op.create_table(
        "scheduled_post_assets",
        sa.Column("scheduled_post_id", sa.Uuid(), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "position BETWEEN 0 AND 9", name=op.f("ck_scheduled_post_assets_position")
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_scheduled_post_assets_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_post_id"],
            ["scheduled_posts.id"],
            name=op.f("fk_scheduled_post_assets_scheduled_post_id_scheduled_posts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_scheduled_post_assets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_post_assets")),
        sa.UniqueConstraint(
            "scheduled_post_id",
            "position",
            name=op.f("uq_scheduled_post_assets_scheduled_post_id_position"),
        ),
    )
    op.create_index(
        op.f("ix_scheduled_post_assets_media_asset_id"),
        "scheduled_post_assets",
        ["media_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_post_assets_workspace_id"),
        "scheduled_post_assets",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_post_targets",
        sa.Column("scheduled_post_id", sa.Uuid(), nullable=False),
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("caption_override", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("poll_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("container_id", sa.Text(), nullable=True),
        sa.Column(
            "child_container_ids",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("platform_media_id", sa.Text(), nullable=True),
        sa.Column("permalink", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("first_comment_platform_id", sa.Text(), nullable=True),
        sa.Column("first_comment_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status <> 'published' OR platform_media_id IS NOT NULL",
            name=op.f("ck_scheduled_post_targets_published_media"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'publishing', 'container_created', 'published', 'failed', 'canceled')",
            name=op.f("ck_scheduled_post_targets_status"),
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND poll_count >= 0", name=op.f("ck_scheduled_post_targets_counters")
        ),
        sa.CheckConstraint(
            "caption_override IS NULL OR char_length(caption_override) <= 2200",
            name=op.f("ck_scheduled_post_targets_caption_override_length"),
        ),
        sa.CheckConstraint(
            "cardinality(child_container_ids) <= 10",
            name=op.f("ck_scheduled_post_targets_children"),
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_post_id"],
            ["scheduled_posts.id"],
            name=op.f("fk_scheduled_post_targets_scheduled_post_id_scheduled_posts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_scheduled_post_targets_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_scheduled_post_targets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_post_targets")),
        sa.UniqueConstraint(
            "scheduled_post_id",
            "social_account_id",
            name=op.f("uq_scheduled_post_targets_scheduled_post_id_social_account_id"),
        ),
    )
    op.create_index(
        "ix_scheduled_post_targets_account_status",
        "scheduled_post_targets",
        ["social_account_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_post_targets_pending",
        "scheduled_post_targets",
        ["scheduled_post_id"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        op.f("ix_scheduled_post_targets_workspace_id"),
        "scheduled_post_targets",
        ["workspace_id"],
        unique=False,
    )
    # No scheduled post existed before this revision, so any stored reference to one is an orphan
    # the new foreign keys would refuse: a link that only named a scheduled post goes, a link that
    # also has its media item keeps it.
    op.execute(
        "DELETE FROM automation_posts WHERE scheduled_post_id IS NOT NULL AND media_item_id IS NULL"
    )
    op.execute(
        "UPDATE automation_posts SET scheduled_post_id = NULL WHERE scheduled_post_id IS NOT NULL"
    )
    op.execute(
        "UPDATE media_items SET published_target_id = NULL WHERE published_target_id IS NOT NULL"
    )
    op.create_index(
        "ix_automation_posts_scheduled_post_id",
        "automation_posts",
        ["scheduled_post_id"],
        unique=False,
        postgresql_where=sa.text("scheduled_post_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_automation_posts_scheduled_post_id_scheduled_posts"),
        "automation_posts",
        "scheduled_posts",
        ["scheduled_post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("uq_media_items_published_target_id"), "media_items", ["published_target_id"]
    )
    op.create_foreign_key(
        op.f("fk_media_items_published_target_id_scheduled_post_targets"),
        "media_items",
        "scheduled_post_targets",
        ["published_target_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_media_items_published_target_id_scheduled_post_targets"),
        "media_items",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("uq_media_items_published_target_id"), "media_items", type_="unique")
    op.drop_constraint(
        op.f("fk_automation_posts_scheduled_post_id_scheduled_posts"),
        "automation_posts",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_automation_posts_scheduled_post_id",
        table_name="automation_posts",
        postgresql_where=sa.text("scheduled_post_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_scheduled_post_targets_workspace_id"), table_name="scheduled_post_targets"
    )
    op.drop_index(
        "ix_scheduled_post_targets_pending",
        table_name="scheduled_post_targets",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index("ix_scheduled_post_targets_account_status", table_name="scheduled_post_targets")
    op.drop_table("scheduled_post_targets")
    op.drop_index(op.f("ix_scheduled_post_assets_workspace_id"), table_name="scheduled_post_assets")
    op.drop_index(
        op.f("ix_scheduled_post_assets_media_asset_id"), table_name="scheduled_post_assets"
    )
    op.drop_table("scheduled_post_assets")
    op.drop_index(op.f("ix_posting_slots_workspace_id"), table_name="posting_slots")
    op.drop_table("posting_slots")
    op.drop_index("ix_scheduled_posts_workspace_publish_at", table_name="scheduled_posts")
    op.drop_index(op.f("ix_scheduled_posts_workspace_id"), table_name="scheduled_posts")
    op.drop_index(
        "ix_scheduled_posts_due",
        table_name="scheduled_posts",
        postgresql_where=sa.text("status IN ('scheduled', 'publishing')"),
    )
    op.drop_table("scheduled_posts")
    op.drop_index("uq_hashtag_groups_workspace_id_lower_name", table_name="hashtag_groups")
    op.drop_index(op.f("ix_hashtag_groups_workspace_id"), table_name="hashtag_groups")
    op.drop_table("hashtag_groups")
    # ### end Alembic commands ###
