"""Ask Social Hood (§5.5 Agent; FR-AGT-01…15, TR-AGT-01…08): agent_runs, agent_steps,
agent_approvals (R2), agent_policies (one per workspace, backfilled for existing workspaces as
read_only with every capability off); ai_usage_events.feature takes agent_turn

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-29 18:04:36.129924+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ai_usage_events.feature before this revision (0009).
FEATURES = (
    "'message_analysis', 'reply_suggestion', 'auto_reply', 'conversation_summary', "
    "'comment_analysis', 'post_summary', 'caption_generation', 'knowledge_test', "
    "'automation_ai_reply'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_policies",
        sa.Column("mode", sa.Text(), server_default=sa.text("'read_only'"), nullable=False),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"send_replies": false, "schedule_messages": false, "schedule_posts": false, "create_automations": false, "delete_automations": false, "bulk_actions": false}\'::jsonb'
            ),
            nullable=False,
        ),
        sa.Column(
            "limits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"bulk_max": 50, "writes_per_hour": 30, "writes_per_day": 200}\'::jsonb'
            ),
            nullable=False,
        ),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(limits) = 'object'", name=op.f("ck_agent_policies_limits")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(permissions) = 'object'", name=op.f("ck_agent_policies_permissions")
        ),
        sa.CheckConstraint(
            "mode IN ('read_only', 'copilot', 'supervised', 'autonomous')",
            name=op.f("ck_agent_policies_mode"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_agent_policies_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_policies_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_policies")),
        sa.UniqueConstraint("workspace_id", name=op.f("uq_agent_policies_workspace_id")),
    )
    op.create_index(
        op.f("ix_agent_policies_workspace_id"), "agent_policies", ["workspace_id"], unique=False
    )
    # Every workspace has its policy row (new ones get it in repositories/workspaces.py).
    op.execute("INSERT INTO agent_policies (workspace_id) SELECT id FROM workspaces")
    op.create_table(
        "agent_runs",
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.Text(), server_default=sa.text("'ask'"), nullable=False),
        sa.Column("request", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column(
            "answer_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("credits", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(answer_refs) = 'array'", name=op.f("ck_agent_runs_answer_refs")
        ),
        sa.CheckConstraint(
            "mode IN ('read_only', 'copilot', 'supervised', 'autonomous')",
            name=op.f("ck_agent_runs_mode"),
        ),
        sa.CheckConstraint("source IN ('ask', 'standing')", name=op.f("ck_agent_runs_source")),
        sa.CheckConstraint(
            "status IN ('queued', 'planning', 'running', 'awaiting_approval', 'succeeded', 'partial', 'failed', 'cancelled', 'expired')",
            name=op.f("ck_agent_runs_status"),
        ),
        sa.CheckConstraint(
            "char_length(request) BETWEEN 1 AND 2000", name=op.f("ck_agent_runs_request_length")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_agent_runs_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index("ix_agent_runs_thread", "agent_runs", ["thread_id", "created_at"], unique=False)
    op.create_index(
        "ix_agent_runs_workspace",
        "agent_runs",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_runs_workspace_id"), "agent_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "agent_steps",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("tool", sa.Text(), nullable=True),
        sa.Column("tier", sa.Text(), nullable=True),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("verification", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "decision IS NULL OR decision ~ '^(execute|approval|refuse:[a-z_]+)$'",
            name=op.f("ck_agent_steps_decision"),
        ),
        sa.CheckConstraint(
            "kind <> 'tool' OR (tool IS NOT NULL AND tier IS NOT NULL)",
            name=op.f("ck_agent_steps_tool"),
        ),
        sa.CheckConstraint(
            "kind IN ('tool', 'condition', 'report')", name=op.f("ck_agent_steps_kind")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'skipped', 'blocked', 'awaiting_approval')",
            name=op.f("ck_agent_steps_status"),
        ),
        sa.CheckConstraint(
            "tier IS NULL OR tier IN ('read', 'draft', 'low', 'high', 'destructive')",
            name=op.f("ck_agent_steps_tier"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_agent_steps_attempts")),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_agent_steps_ordinal")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_steps_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_steps_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_steps")),
        sa.UniqueConstraint("run_id", "ordinal", name=op.f("uq_agent_steps_run_id_ordinal")),
    )
    op.create_index(
        op.f("ix_agent_steps_workspace_id"), "agent_steps", ["workspace_id"], unique=False
    )
    op.create_table(
        "agent_approvals",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired', 'superseded')",
            name=op.f("ck_agent_approvals_status"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_agent_approvals_decided_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_approvals_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["agent_steps.id"],
            name=op.f("fk_agent_approvals_step_id_agent_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_approvals_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_approvals")),
    )
    op.create_index(op.f("ix_agent_approvals_run_id"), "agent_approvals", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_agent_approvals_workspace_id"), "agent_approvals", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_agent_approvals_pending",
        "agent_approvals",
        ["step_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_ai_usage_events_feature"), "ai_usage_events", type_="check")
    op.create_check_constraint(
        op.f("ck_ai_usage_events_feature"),
        "ai_usage_events",
        f"feature IN ({FEATURES}, 'agent_turn')",
    )


def downgrade() -> None:
    op.execute("DELETE FROM ai_usage_events WHERE feature = 'agent_turn'")
    op.drop_constraint(op.f("ck_ai_usage_events_feature"), "ai_usage_events", type_="check")
    op.create_check_constraint(
        op.f("ck_ai_usage_events_feature"), "ai_usage_events", f"feature IN ({FEATURES})"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_agent_approvals_pending",
        table_name="agent_approvals",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_agent_approvals_workspace_id"), table_name="agent_approvals")
    op.drop_index(op.f("ix_agent_approvals_run_id"), table_name="agent_approvals")
    op.drop_table("agent_approvals")
    op.drop_index(op.f("ix_agent_steps_workspace_id"), table_name="agent_steps")
    op.drop_table("agent_steps")
    op.drop_index(op.f("ix_agent_runs_workspace_id"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_workspace", table_name="agent_runs")
    op.drop_index("ix_agent_runs_thread", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_agent_policies_workspace_id"), table_name="agent_policies")
    op.drop_table("agent_policies")
    # ### end Alembic commands ###
