"""P8 billing and notifications (§5.3, §5.8, §5.9; TR-BIL-02, FR-NOT-02…04, TR-FE-09):
payments (Dodo payment events), push_subscriptions (user-scoped, one row per browser endpoint),
email_deliveries (the email outbox, unique per workspace and dedupe key), weekly_digests (one per
workspace per ISO week); webhook_events.occurred_at (the provider's event time, for ordering);
notifications.pushed_at and a check on notifications.channels (in_app, email, push). Workspaces
without a subscription row get a Free one (provisioning creates it for new workspaces).

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-29 22:43:46.163266+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("endpoint ~ '^https://'", name=op.f("ck_push_subscriptions_endpoint")),
        sa.CheckConstraint("failure_count >= 0", name=op.f("ck_push_subscriptions_failure_count")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_push_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_push_subscriptions_endpoint")),
    )
    op.create_index(
        op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("dodo_payment_id", sa.Text(), nullable=False),
        sa.Column("dodo_subscription_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invoice_url", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_payments_currency")),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed', 'refunded', 'pending')",
            name=op.f("ck_payments_status"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_payments_amount_minor")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_payments_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("dodo_payment_id", name=op.f("uq_payments_dodo_payment_id")),
    )
    op.create_index(
        "ix_payments_recent",
        "payments",
        ["workspace_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_payments_workspace_id"), "payments", ["workspace_id"], unique=False)
    op.create_table(
        "weekly_digests",
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("recipients", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'skipped', 'failed')",
            name=op.f("ck_weekly_digests_status"),
        ),
        sa.CheckConstraint(
            "EXTRACT(ISODOW FROM week_start) = 1", name=op.f("ck_weekly_digests_week_start")
        ),
        sa.CheckConstraint("recipients >= 0", name=op.f("ck_weekly_digests_recipients")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_weekly_digests_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weekly_digests")),
        sa.UniqueConstraint(
            "workspace_id", "week_start", name=op.f("uq_weekly_digests_workspace_id_week_start")
        ),
    )
    op.create_index(
        op.f("ix_weekly_digests_workspace_id"), "weekly_digests", ["workspace_id"], unique=False
    )
    op.create_table(
        "email_deliveries",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("notification_id", sa.Uuid(), nullable=True),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("to_email", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status <> 'sent' OR sent_at IS NOT NULL", name=op.f("ck_email_deliveries_sent_at")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'sending', 'sent', 'failed', 'skipped')",
            name=op.f("ck_email_deliveries_status"),
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_email_deliveries_notification_id_notifications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_deliveries_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_email_deliveries_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_deliveries")),
        sa.UniqueConstraint(
            "workspace_id", "dedupe_key", name=op.f("uq_email_deliveries_workspace_id_dedupe_key")
        ),
    )
    op.create_index(
        "ix_email_deliveries_queued",
        "email_deliveries",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        op.f("ix_email_deliveries_user_id"), "email_deliveries", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_deliveries_workspace_id"), "email_deliveries", ["workspace_id"], unique=False
    )
    op.add_column(
        "notifications", sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "webhook_events", sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_notifications_channels"),
        "notifications",
        "channels <@ ARRAY['in_app', 'email', 'push']::text[]",
    )
    # Every workspace has one subscription row (F-01); a Free one for any that lacks it.
    op.execute(
        """
        INSERT INTO subscriptions (workspace_id, plan, status, billing_anchor_day)
        SELECT w.id, 'free', 'free', LEAST(EXTRACT(DAY FROM w.created_at)::int, 28)
          FROM workspaces w
         WHERE NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.workspace_id = w.id)
        """
    )


def downgrade() -> None:
    # The backfilled Free subscriptions stay: they are what provisioning creates anyway.
    op.drop_constraint(op.f("ck_notifications_channels"), "notifications", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook_events", "occurred_at")
    op.drop_column("notifications", "pushed_at")
    op.drop_index(op.f("ix_email_deliveries_workspace_id"), table_name="email_deliveries")
    op.drop_index(op.f("ix_email_deliveries_user_id"), table_name="email_deliveries")
    op.drop_index(
        "ix_email_deliveries_queued",
        table_name="email_deliveries",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("email_deliveries")
    op.drop_index(op.f("ix_weekly_digests_workspace_id"), table_name="weekly_digests")
    op.drop_table("weekly_digests")
    op.drop_index(op.f("ix_payments_workspace_id"), table_name="payments")
    op.drop_index("ix_payments_recent", table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    # ### end Alembic commands ###
